linters-settings:
  gocritic:
    disabled-checks:
      - ifElseChain
      - elseif

linters:
  disable-all: true
  enable:
    - gocritic
    - unconvert
    - govet
    - gosimple
    - rowserrcheck
    - ineffassign
    - sqlclosecheck
    - noctx
